import {
  FaFacebookF, FaLinkedinIn, FaInstagram, FaWhatsapp,
  FaMapMarkerAlt, FaPhone, FaEnvelope, FaClock, FaArrowRight, FaArrowUp,
  FaCode, FaHeart, FaSnapchat, FaPalette, FaLaptopCode,
  FaMobileAlt, FaDatabase, FaServer, FaShieldAlt, FaRocket,
  FaHandshake, FaLightbulb, FaGem, FaProjectDiagram, FaUsers,
  FaTrophy, FaGlobe, FaPaperPlane, FaUser,
  FaBuilding, FaCommentAlt, FaCheckCircle, FaDirections, FaChevronDown,
  FaCogs, FaTools, FaChartBar, FaCloud, FaSearch,
  FaBriefcase, FaHome, FaInfoCircle, FaCheck, FaTimes,
  FaLock, FaShareAlt, FaEye, FaDesktop, FaTabletAlt, FaMobile,
  FaMicrochip, FaBrain, FaRobot, FaCodeBranch, FaTerminal, FaLaptop,
  FaSitemap, FaLightbulb as FaIdea, FaRocket as FaLaunch, FaStore, FaMap, FaTiktok,
  FaUserShield,
} from 'react-icons/fa';
import { FaXTwitter } from 'react-icons/fa6';

import {
  SiReact, SiJavascript, SiNodedotjs, SiPython, SiDocker,
  SiGit, SiTypescript, SiAngular, SiVuedotjs, SiNextdotjs,
  SiTailwindcss, SiBootstrap, SiHtml5, SiCss3, SiPhp,
  SiLaravel, SiPostgresql, SiMysql, SiMongodb, SiRedis, SiFirebase,
  SiGooglecloud, SiNetlify, SiVercel, SiLinux, SiApple, SiAndroid,
  SiFigma, SiRedux, SiGraphql,
} from 'react-icons/si';

import {
  BsCodeSlash, BsShieldCheck, BsHeadset, BsRocketTakeoff,
  BsGear, BsLockFill, BsBriefcaseFill, BsChatLeftDotsFill,
  BsDisplayFill, BsLaptopFill, BsPhoneFill, BsCpuFill,
  BsGridFill, BsLightningFill, BsCloudCheckFill,
  BsPeopleFill, BsPersonFill, BsStarFill,
  BsHandThumbsUpFill, BsHeartFill, BsEnvelopeFill, BsTelephoneFill,
  BsGeoAltFill, BsGraphUp,
} from 'react-icons/bs';

import { IoCloseCircleOutline, IoSettingsOutline, IoSearchOutline, IoMenuOutline } from 'react-icons/io5';

import { HiOutlineLightBulb, HiOutlineDatabase, HiOutlineCloud } from 'react-icons/hi';

import { MdOutlineDeveloperMode, MdOutlineSecurity, MdOutlineAnalytics } from 'react-icons/md';

export const iconMap = {
  facebook: FaFacebookF,
  twitter: FaXTwitter,
  x: FaXTwitter,
  linkedin: FaLinkedinIn,
  instagram: FaInstagram,
  whatsapp: FaWhatsapp,
  snapchat: FaSnapchat,
  mapMarker: FaMapMarkerAlt,
  phone: FaPhone,
  envelope: FaEnvelope,
  clock: FaClock,
  arrowRight: FaArrowRight,
  arrowUp: FaArrowUp,
  code: FaCode,
  heart: FaHeart,
  palette: FaPalette,
  laptopCode: FaLaptopCode,
  mobileAlt: FaMobileAlt,
  database: FaDatabase,
  server: FaServer,
  shieldAlt: FaShieldAlt,
  rocket: FaRocket,
  handshake: FaHandshake,
  lightbulb: FaLightbulb,
  gem: FaGem,
  projectDiagram: FaProjectDiagram,
  users: FaUsers,
  trophy: FaTrophy,
  globe: FaGlobe,
  paperPlane: FaPaperPlane,
  user: FaUser,
  building: FaBuilding,
  commentAlt: FaCommentAlt,
  checkCircle: FaCheckCircle,
  directions: FaDirections,
  chevronDown: FaChevronDown,
  cogs: FaCogs,
  tools: FaTools,
  chartBar: FaChartBar,
  cloud: FaCloud,
  search: FaSearch,
  briefcase: FaBriefcase,
  home: FaHome,
  infoCircle: FaInfoCircle,
  check: FaCheck,
  times: FaTimes,
  lock: FaLock,
  shareAlt: FaShareAlt,
  eye: FaEye,
  desktop: FaDesktop,
  tabletAlt: FaTabletAlt,
  mobile: FaMobile,
  microchip: FaMicrochip,
  brain: FaBrain,
  robot: FaRobot,
  codeBranch: FaCodeBranch,
  terminal: FaTerminal,
  laptop: FaLaptop,
  sitemap: FaSitemap,
  idea: FaIdea,
  launch: FaLaunch,
  store: FaStore,
  map: FaMap,
  tiktok: FaTiktok,
  userShield: FaUserShield,

  react: SiReact,
  javascript: SiJavascript,
  nodejs: SiNodedotjs,
  python: SiPython,
  docker: SiDocker,
  git: SiGit,
  typescript: SiTypescript,
  angular: SiAngular,
  vue: SiVuedotjs,
  nextjs: SiNextdotjs,
  tailwindcss: SiTailwindcss,
  bootstrap: SiBootstrap,
  html5: SiHtml5,
  css3: SiCss3,
  php: SiPhp,
  laravel: SiLaravel,
  postgresql: SiPostgresql,
  mysql: SiMysql,
  mongodb: SiMongodb,
  redis: SiRedis,
  firebase: SiFirebase,
  googlecloud: SiGooglecloud,
  netlify: SiNetlify,
  vercel: SiVercel,
  linux: SiLinux,
  apple: SiApple,
  android: SiAndroid,
  figma: SiFigma,
  redux: SiRedux,
  graphql: SiGraphql,

  codeSlash: BsCodeSlash,
  shieldCheck: BsShieldCheck,
  headset: BsHeadset,
  rocketTakeoff: BsRocketTakeoff,
  gear: BsGear,
  lockFill: BsLockFill,
  briefcaseFill: BsBriefcaseFill,
  chatDots: BsChatLeftDotsFill,
  displayFill: BsDisplayFill,
  laptopFill: BsLaptopFill,
  phoneFill: BsPhoneFill,
  cpuFill: BsCpuFill,
  gridFill: BsGridFill,
  lightningFill: BsLightningFill,
  cloudCheck: BsCloudCheckFill,
  peopleFill: BsPeopleFill,
  personFill: BsPersonFill,
  starFill: BsStarFill,
  thumbsUp: BsHandThumbsUpFill,
  heartFill: BsHeartFill,
  envelopeFill: BsEnvelopeFill,
  telephoneFill: BsTelephoneFill,
  geoAltFill: BsGeoAltFill,
  graphUp: BsGraphUp,

  closeCircle: IoCloseCircleOutline,
  settings: IoSettingsOutline,
  searchOutline: IoSearchOutline,
  menu: IoMenuOutline,

  ideaOutline: HiOutlineLightBulb,
  dbOutline: HiOutlineDatabase,
  cloudOutline: HiOutlineCloud,

  devMode: MdOutlineDeveloperMode,
  security: MdOutlineSecurity,
  analytics: MdOutlineAnalytics,
};
